### ISSUE TITLE
Unknown option -d

### ISSUE THREAD

**Issue by mralexho** [aquifer/aquifer#121]
While trying to create a new D8 project, the command as indicated on https://github.com/aquifer/aquifer#1-create-an-aquifer-project returns:

```
  error: unknown option `-d'
```

**Comment by patrickocoffeyo** [comment]
At the moment, Aquifer has 2 branches: the branch that is published to npm (`dev`) and the branch that is holding our 1.0.0 sprint (`1.0.0`). The `-d` flag only exist in the `1.0.0` branch. I'll update our default branch so that it's `dev` again so the documentation will be at the NPM version.

If you would like to use Aquifer with Drupal 8, follow the "Installing for development" instructions [here](http://docs.aquifer.io/sections/installing-aquifer.html), and make sure Aquifer's repository is set to the `1.0.0` branch.

**Comment by patrickocoffeyo** [comment]
@mralexho We also pushed a pre-release tag to npm, so you can install the 1.0 branch very easily:

```
npm install -g aquifer@1.0.0-beta1
```
